# Generated by Django 3.1.2 on 2020-11-14 11:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(default=50, max_length=50, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
