# Generated by Django 3.1.2 on 2021-02-08 03:21

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video1',
            field=models.FileField(blank=True, default='default.mp4', null=True, upload_to=products.models.upload_product_video_path),
        ),
        migrations.AddField(
            model_name='product',
            name='video2',
            field=models.FileField(blank=True, default='default.mp4', null=True, upload_to=products.models.upload_product_video_path),
        ),
        migrations.AddField(
            model_name='product',
            name='video3',
            field=models.FileField(blank=True, default='default.mp4', null=True, upload_to=products.models.upload_product_video_path),
        ),
        migrations.AddField(
            model_name='product',
            name='video4',
            field=models.FileField(blank=True, default='default.mp4', null=True, upload_to=products.models.upload_product_video_path),
        ),
    ]
