# Generated by Django 3.1.2 on 2021-02-08 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210208_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='video2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='video3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='video4',
        ),
    ]
