# Generated by Django 3.0.8 on 2020-07-31 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='file',
            new_name='img',
        ),
    ]
