# Generated by Django 3.0.8 on 2020-10-19 17:13

import Home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_auto_20201019_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='default.jpg', upload_to=Home.models.upload_image_path),
        ),
    ]
