# Generated by Django 3.0.8 on 2020-10-19 17:55

import Home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_auto_20201019_2243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'get_latest_by': 'join_date', 'ordering': ['user'], 'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='img',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
        migrations.AddField(
            model_name='profile',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=Home.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='profile',
            name='tel',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
    ]
